//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevitPluginWalls25.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RevitPluginWalls25.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RevitPluginWalls25.dll.
        /// </summary>
        public static string AssembleName {
            get {
                return ResourceManager.GetString("AssembleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 845DA8A5-E76A-43D4-AC1A-A5803802D064.
        /// </summary>
        public static string DataStorageGuid {
            get {
                return ResourceManager.GetString("DataStorageGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WallPluginSettings.
        /// </summary>
        public static string DataStorageName {
            get {
                return ResourceManager.GetString("DataStorageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\tmp\revit.
        /// </summary>
        public static string DebugAppPath {
            get {
                return ResourceManager.GetString("DebugAppPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RevitPluginWalls.Startup.
        /// </summary>
        public static string EntryPoint {
            get {
                return ResourceManager.GetString("EntryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить данные..
        /// </summary>
        public static string FailAPIMessage {
            get {
                return ResourceManager.GetString("FailAPIMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Построение не выполнено..
        /// </summary>
        public static string FailMessage {
            get {
                return ResourceManager.GetString("FailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string ImageFolderName {
            get {
                return ResourceManager.GetString("ImageFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плагин построения стен.
        /// </summary>
        public static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autodesk\Revit\Addins\2022\RevitPluginWalls.
        /// </summary>
        public static string ReleaseAppPath {
            get {
                return ResourceManager.GetString("ReleaseAppPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Построить стены.
        /// </summary>
        public static string RibbonBtnName {
            get {
                return ResourceManager.GetString("RibbonBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки, затем автоматическое построение стен.
        /// </summary>
        public static string RibbonBtnNameTips {
            get {
                return ResourceManager.GetString("RibbonBtnNameTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматические построения.
        /// </summary>
        public static string RibbonSectionName {
            get {
                return ResourceManager.GetString("RibbonSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Построение завершено..
        /// </summary>
        public static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
    }
}
